### ISSUE TITLE
Doubts for Step 3 - GNPS and Cytoscape

### ISSUE THREAD

**Issue by ChangRenAU** [DorresteinLaboratory/Bioactive_Molecular_Networks#14]
In Cytoscape, use the Select function to select the nodes with significant bioactivity (typical threshold would be r2 > 0.8 and p-value < -0.02). 

How to determine the threshold for our own data? Should it be same with yours?

**Comment by lfnothias** [comment]
Note that these are fairly conservative values. You might wanna lower the r2.

One way to see this is -> set the values so you have enough lead candidate to investigate in the network. 
Bioactivity based molecular networking generates hypothesis of bioactive candidates, and additional experiment/orthogonal informations (such as network annotation), should be used to help interpret.

**Comment by czr0049** [comment]
> Note that these are fairly conservative values. You might wanna lower the r2.
> 
> One way to see this is -> set the values so you have enough lead candidate to investigate in the network.
> Bioactivity based molecular networking generates hypothesis of bioactive candidates, and additional experiment/orthogonal informations (such as network annotation), should be used to help interpret.

**Comment by ChangRenAU** [comment]
By “orthogonal informations (such as network annotation),” do you mean that we should determine the structure first during MS and then do the annotation in the network?
What additional experiments can we use to interpret the data? Should we isolate and test the compounds?

**Comment by lfnothias** [comment]
The way to see this: is bioactivity scoring helps to prioritise the ions to focus interpretation on You can use molecular networking or other MS/MS tool (MS2LDA etc) to annotate the ions with (sub)-structure to help interpretation. To validate the hypothesis, yes indeed one would have to isolate the compound.

**Comment by ChangRenAU** [comment]
Appreciate your timely response, but I still have some doubts:
1. What is the upper or lower limit of the correlation coefficient and p_value_corrected? How were these two limits established? What are the criteria/rationale to select the appropriate correlation coefficient and p_value_corrected for each experiment?
2. There are several handle positions(p_value_corrected = 0.03, 0.05) needed to control the size of the node, what is the rationale to define these values?

**Comment by ridasilva** [comment]
Hello,

we are calculating pearson correlation
https://en.wikipedia.org/wiki/Pearson_correlation_coefficient

It ranges from -1 (your metabolite intensity is perfectly uncorrelated with your bioactivity) to 1 (your metabolite intensity is perfectly correlated with your bioactivity). The p_value is corrected by bonferroni, which is very stringent, so, anything below 0.05 should be trustworthy.

The general rules to interpret pearson correlation for continuous data can be applied here.

Cheers,
Ricardo
