### ISSUE TITLE
MZMine workflow link not working

### ISSUE THREAD

**Issue by davidwhealey** [DorresteinLaboratory/Bioactive_Molecular_Networks#15]
The link for Step 1 in the docs

> Process your data following instructions described in the GNPS data analysis workflow 2.0 (https://bix-lab.ucsd.edu/display/Public/GNPS+data+analysis+workflow+2.0#GNPSdataanalysisworkflow2.0-GNPSdataanalysisworkflow2.0%3AOFFLINEversion). 

Does not appear to be working

**Comment by lfnothias** [comment]
Thanks a lot ! Indeed, it was pointing to our old documentation. I have now updated all the links in the readme file.
