### ISSUE TITLE
Visualizing Jupyter results in cytoscape

### ISSUE THREAD

**Issue by SephoraMutombo** [DorresteinLaboratory/Bioactive_Molecular_Networks#17]
Hi,

I am new to cytoscape. I am struggling to open the output file from jupyter in my FBMN network. When I import the table by choosing "source node attribute" for all my columns except for the first (source node) and the second (target node) ones, I am not able to filter nodes with "cor" and "p-value corrected" in the required ranges. Which column data type is appropriate for my columns?

![Cytoscape screenshot](https://user-images.githubusercontent.com/75777133/113994846-009f9580-9856-11eb-9e00-8d58d65fa758.PNG)

I will appreciate your help.

Kind regards,
Sephora

**Comment by lfnothias** [comment]
Hi Sephora,
I recommend using the "Filter" tool panel (left side of the screen). There you can filter nodes based on attribute(s) values. Once selected based on defined criteria, one can bypass the style of these nodes (Style panel, left also) for enhance visualisation. For example changing the shape or color of these nodes meeting the criteria. 
I hope that will provide interesting insight. Let me know if you have other questions.

**Comment by SephoraMutombo** [comment]
Good day,

Thank you. I'm getting error messages after importing my table (see screenshots attached).

![Capture2 cytoscape](https://user-images.githubusercontent.com/75777133/114158514-09ab6800-9925-11eb-949e-1952b669e4d1.PNG)
![Capture3 cytoscape](https://user-images.githubusercontent.com/75777133/114158537-129c3980-9925-11eb-9f93-303c158e429d.PNG).

Best regards,
Sephora

**Comment by lfnothias** [comment]
This might have to do with the formatting and/or the type of columns imported (likely inconsistency for column type: integer, float, etc)..
I would recommend to start by selecting only couple columns (node attributes) in the Cytoscape interface. Then make sure the format type and format is looking okay in that preview interface before effectively importing them. If successful, then you can import more columns until you find what which columns are causing troubles.

**Comment by lfnothias** [comment]
Okay, actually it looks like you are importing the table as a network table. Instead, that present table should be imported as a node attribute table on your existing FBMN network.

**Comment by SephoraMutombo** [comment]
Solved. 
Thank you for your help. I was able to import the table as you suggested. 

Now I have a another issue. I have error messages in my p_value_corrected column every time the value is not 1 (see picture attached). Is there a way to solve it?
![Capture6](https://user-images.githubusercontent.com/75777133/114388711-5cd72200-9b94-11eb-8f1f-4480e5165b3f.PNG)

Regards,
Sephora

**Comment by lfnothias** [comment]
Awesome. It seems that the column `p_value_corrected` is not recognized as float type. Please check the type is selected properly when importing. Otherwise it could be the digit separator (. or ,) depending on your operating system configuration. Or it could be mixed type on characters in the column (like some string in the some entries). In the latter case, you would have to remove anything that is not a number.

**Comment by SephoraMutombo** [comment]
Solved. I didn't chose the proper type for it "floating point". 
Now everything is fine. Thank you once more for your assistance.

Regards
