### ISSUE TITLE
Add the value of the bioassay experiments

### ISSUE THREAD

**Issue by YuChiLin7051** [DorresteinLaboratory/Bioactive_Molecular_Networks#18]
Dear Professor:
In the original article, SI values were used to select bioactivity data. Can IC50 values be converted and input instead? Would the input of IC50 values require adjusting other parameters before the subsequent calculation, as it might lead to reversed outcomes?

**Comment by rsilvabioinfo** [comment]
Hi,

any quantitative continuous value can be used to calculate correlations.

Cheers,
Ricardo

Em qui., 9 de nov. de 2023 às 01:30, YuChiLin7051 ***@***.***>
escreveu:
