### ISSUE TITLE
How to import Columns from Table?

### ISSUE THREAD

**Issue by YuChiLin7051** [DorresteinLaboratory/Bioactive_Molecular_Networks#19]
Dear professor:

As the picture, to import columns from the output file named features_quantification_matrix_transposed_with_significant_correlation_pvalue_corrected.
What insertion option should I choose?

![2023-11-10_164754](https://github.com/DorresteinLaboratory/Bioactive_Molecular_Networks/assets/150316340/81507e3c-52d9-4713-bc8f-fd8196a58307)

**Comment by lfnothias** [comment]
Sorry for overlooking the message. It should be the same solution as in https://github.com/DorresteinLaboratory/Bioactive_Molecular_Networks/issues/21
