### ISSUE TITLE
coding errors

### ISSUE THREAD

**Issue by DUCDATLE** [DorresteinLaboratory/Bioactive_Molecular_Networks#20]
Writing code errors:
I am new code writing. Thank you very much for patient help me to solve the problem.
I am making the code and run. However, there is error as attached picture.
What should I do.
Thank you in advanced.

![coding error1](https://github.com/DorresteinLaboratory/Bioactive_Molecular_Networks/assets/155708073/4bf0aee5-3364-4989-bfc5-03e098d53bfc)

**Comment by lfnothias** [comment]
Hi, are you using only two samples ? It is weird that you have rows with NA in your table.

**Comment by DUCDATLE** [comment]
Yes, I run two samples with one activity.
NA are the blank data

**Comment by lfnothias** [comment]
Ok then it makes sense. For correlation analysis, two data points aren't sufficient. More is needed.

**Comment by DUCDATLE** [comment]
I got it. Thank you so much!

**Comment by lfnothias** [comment]
Your welcome. Best of luck with your next attempt
