### ISSUE TITLE
Adding output data and visualization in the cytoscape

### ISSUE THREAD

**Issue by DUCDATLE** [DorresteinLaboratory/Bioactive_Molecular_Networks#21]
I am new cytoscape. I am visualize the output table generated from jupyter data into cytoscape. Could you guide me step by step how to do.
Should I import the output table generated from jupyter data by import the node table function to the exist feature base molecular network which was generated from GNPS after run the mzmine data through GNPS website?
Thank Prof. Dr. lfnothias very much for your patient.
Best regard,
Ducdat.

**Comment by lfnothias** [comment]
Hi, open a feature based molecular networking results in Cytoscape > go for import note table and proceed with the import from the bioactivity based MN. It should work as straight out of the box. Just make sure the column feature_ID is selected as key map.

**Comment by DUCDATLE** [comment]
Prof. Dr. lfnothias,
Thank you very much for quickly response. I had already tried many times to follow your guideline. Therefore, I made a late response to you by today. However, I still can not import the node table into the feature network by using the Cytoscape program as mentioned with the attachment. Would you please tell me what is the problem and how could I solve the problem.
Once again, I am appreciate your help and thank you so much for your time !
Best regard,
Ducdat Le.


![cystoscape error](https://github.com/DorresteinLaboratory/Bioactive_Molecular_Networks/assets/155708073/cd45a09c-4735-41ef-9c09-418e05041907)

**Comment by lfnothias** [comment]
Hi Ducdatle,

Instead of having the key symbol on the IDs column, try clicking on the “shared name” column (that key symbol will show there) and that should work.

**Comment by DUCDATLE** [comment]
It had been worked well. Thank Professor very much for your help.
Sincerely,
Ducdat Le.
