### ISSUE TITLE
Issue regarding running of Jupyter notebook

### ISSUE THREAD

**Issue by Neelutpal** [DorresteinLaboratory/Bioactive_Molecular_Networks#7]
I have got the following error message while tried to run Jupyter notebook.
I have installed R v3.5 and python 3.6. I wanted install python 2.7 as given in your instruction but, after installation of python 2.7 I was unable to install the packages (pip install six pandas protobuf pymspec pyopenms) and C:\Python27\Scripts folder was also not there. But After installation of python 3.6 the package installation issue and script folder issue was solved. Now when i am trying to run the jupyter notebook, I found the error messages. Screenshots are attached herewith.
![2](https://user-images.githubusercontent.com/31981870/41334686-2027b58c-6f04-11e8-965b-d4b66dc581e9.png)
![untitled](https://user-images.githubusercontent.com/31981870/41334688-207f6c28-6f04-11e8-9dcf-fa82327691e8.png)

**Comment by rsilvabioinfo** [comment]
Hi @Neelutpal,
thank for trying to use the notebook. This notebook uses an R kernel, please try to install it
https://github.com/IRkernel/IRkernel

and give it another try.

**Comment by Neelutpal** [comment]
Thank you.. I will try it...
