### ISSUE TITLE
Installation of IRkernel

### ISSUE THREAD

**Issue by Neelutpal** [DorresteinLaboratory/Bioactive_Molecular_Networks#8]
What might be the reason?
![3](https://user-images.githubusercontent.com/31981870/41336973-7bb2520c-6f0b-11e8-8a6d-60722a7c6c57.png)

**Comment by Neelutpal** [comment]
![4](https://user-images.githubusercontent.com/31981870/41346137-48436d30-6f23-11e8-86e2-f3452c0f0100.png)
![5](https://user-images.githubusercontent.com/31981870/41346138-489c93c4-6f23-11e8-8a73-fb80741e8027.png)
I think IRkernel instaaltion has been succeed. But after uploading the jupyter notebook file and template .csv file it has automatically shown the results as given in the screenshot. Is it OK? As in the procedure is written that we have to execute run command (Cell/Run). If it is OK, then how to export the result file or it will also exported automatically?

**Comment by rsilvabioinfo** [comment]
The results should be saved in the same directory that the notebook is.
